### PR TITLE
Changed the first code sample to use VerticalLayout instead of Div

### PR DESCRIPTION
**Pull request by samie**
Introduce new users with more high-level API first.

## Description

This was discussed more widely earlier, but primarily we should introduce using high-level component API for new Vaadin users, and creating a Div might be misleading.

### CODE REVIEW

**Review by tarekoraby — CHANGES_REQUESTED** [review]
Isn't `addComponents()` a Framework 8 thing? It should remain `add()` I think.

**Review by magi42 — APPROVED** [review]
OK. The purpose of using Div there was just to demonstrate the use of regular HTML elements along with Vaadin components. It apparently wasn't appropriate in that case, so maybe need to demonstrate it in some other way in this or other place.

**Comment by tarekoraby** [comment]
@jouni I think `addComponents()` in this PR is nonexistent in v10+.

**Comment by jouni** [comment]
I damn, I thought someone already changes that.

**Comment by jouni** [comment]
Updated in https://github.com/vaadin/docs/commit/d44c3d1b622003df893f1eb73bfee1f25051dba8

**Pull request merged**
