### PR TITLE
Add a section of integrating Vaading with an existing Quarkus app

### PR DESCRIPTION
**Pull request by preslavrachev**

### CODE REVIEW

**Review by mcollovati — CHANGES_REQUESTED** [review]
Some minor changes, otherwise content looks good to me.

**Comment by preslavrachev** [comment]
> Some minor changes, otherwise content looks good to me.

LGTM, accepted them all. Feel free to proceed.

**Review by mcollovati — APPROVED** [review]
LGTM
Waiting for language check

**Comment by preslavrachev** [comment]
@mcollovati I see this is still pending. Is there anything else that needs to be done on my side?

**Comment by mcollovati** [comment]
@preslavrachev all is ok on your side.
The PR needs to pass our internal language check process. It may require some time.
ping @russelljtdyer

**Comment by mcollovati** [comment]
@russelljtdyer it looks like @preslavrachev already signed the CLA, but for some reason there are two entries

**Pull request merged**
