### PR TITLE
Update unit-and-integration-testing.adoc

### LINKED ISSUE #981: Documentation how to mock UI.getCurrent() and similar in tests
It would be helpful for Vaadin users to be able to unit-test components that depend on UI.getCurrent() and similar, which is exactly what [karibu-testing](https://github.com/mvysny/karibu-testing) provides. Could you please add a link to karibu-testing into the `unit-and-integration-testing.adoc` page?

### PR DESCRIPTION
**Pull request by mvysny**
Fixes #981

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes #981 

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by jouni** [comment]
Would this apply to V22 as well, or is it V14 only?

**Comment by mvysny** [comment]
Hi, both vaadin 14 and 21+

**Review by jouni — APPROVED** [review]

**Comment by jouni** [comment]
I removed the karibu-testing endorsement for now, as we don't have an agreement how we want to promote community-driven projects.

**Comment by jouni** [comment]
Picked to latest in https://github.com/vaadin/docs/commit/99de49f9db7847bc2d3d310edd1c8dc9e3fd7020

**Pull request merged**
