### PR TITLE
Reference Vaadin 14 to 23 upgrade instructions from upgrade tool

### PR DESCRIPTION
**Pull request by tarekoraby**

### CODE REVIEW

**Comment by tarekoraby** [comment]
I had to remove the `[discrete]` from the headers because otherwise, the structure of the document gets messed up, and the instructions are no longer displayed correctly according to the selected versions. Instead of `[discrete]`, the links are removed manually from the tool.

**Comment by jouni** [comment]
Perhaps a proper fix would be to not prefix in-page links/anchors in DSP/docs-app. 

I’m not 100% sure, but I think Gatsby’s `<Link>` component prefixes in-page anchor links here: https://github.com/vaadin/docs-app/blob/master/src/components/ArticleContent.tsx#L89-L104

**Comment by tarekoraby** [comment]
If we choose to fix it, then it shouldn’t be for the sake of the upgrade tool given that it will possibly retire soon.

**Comment by jouni** [comment]
Right. In that case, let’s use this workaround you implemented.

**Pull request merged**
