### PR TITLE
docs: add autoselect example

### PR DESCRIPTION
**Pull request by ugur-vaadin**
Add Java example for the usage of `setAutoselect` for `Tabs`.

Fixes #[3546](https://github.com/vaadin/flow-components/issues/3546) partially.

### CODE REVIEW

**Comment by jouni** [comment]
Based on the description in the docs, I don't understand what “autoselect” does in Tabs.

**Comment by ugur-vaadin** [comment]
Sure, here is the [issue](https://github.com/vaadin/flow-components/issues/3546). I was still tinkering on the example so it is a draft.

**Comment by jouni** [comment]
Should there be a TypeScript version of the example?

**Comment by web-padawan** [comment]
Yes, this is a Flow only feature. Check out the relevant JavaDoc here: https://github.com/vaadin/vaadin-tabs-flow/pull/108/commits/386f205c4c880303d8d8287b426661a54df0e9b1

> The first added `Tab`component will be automatically selected, firing a `SelectedChangeEvent`, unless autoselection is explicitly disabled with `Tabs(boolean, Tab...)`, or `setAutoselect(boolean)`.

**Comment by jouni** [comment]
Alright. Then it needs to be mentioned. We've used the section heading for that (see Grid row editor).

**Comment by ugur-vaadin** [comment]
> Alright. Then it needs to be mentioned. We've used the section heading for that (see Grid row editor).

Addressed in the latest commit.

**Review by jouni — APPROVED** [review]

**Pull request merged**
