### PR TITLE
Changed to use JUnit 5

### PR DESCRIPTION
**Pull request by mstahv**
related pr for the example project: https://github.com/vaadin/flow-crm-tutorial/pull/99

Let's still agree if we want both junit 4 & 5 for the project before merging both.

### CODE REVIEW

**Comment by mstahv** [comment]
I tried to find a solution to use Junit 5 to control the TestBench test in the tutorial today, but didn't get any good solution done. So I guess it is either to accept both JUnit 4 & 5 usage in the same app or to postpone this change until TestBench gets updated.

**Comment by MarcinVaadin** [comment]
Testbench 9 with JUnit5 updates pushed to https://github.com/vaadin/docs/pull/1865

**Comment by jouni** [comment]
@mstahv, are you still working on this PR? Anything missing from it, or can we merge it?

**Comment by mstahv** [comment]
Let's merge it. JUnit 5 is mainstream, so let's use it where possible. The only downside is that people will notice that they can't really use JUnit 5 with testbench yet. Hopefully we could still get TestBench for V24 to support JUnit 5, V24 will have a long life ahead still.... (cc: @mshabarov)

**Review by jouni — APPROVED** [review]

**Comment by jouni** [comment]
> The only downside is that people will notice that they can't really use JUnit 5 with testbench yet

That should be covered by https://github.com/vaadin/docs/pull/1865

**Pull request merged**
