### PR TITLE
Added missing word 'from'.

### PR DESCRIPTION
**Pull request by markhm**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by jouni** [comment]
Please sign the contributor license agreement so we can merge this, thanks!

**Review by jouni — APPROVED** [review]

**Comment by markhm** [comment]
Hi Jouni,

I think I've done that in the past. I could not immediately see a link.

Of course, you can use any suggestions I submit.

Best, Mark

**Comment by tarekoraby** [comment]
Hi @markhm! This is the link: https://cla-assistant.io/vaadin/docs?pullRequest=1040

**Comment by markhm** [comment]
Thanks.

I am looking into the CLA assistant now. I am hesitant to sign, because
wants read access to my Github organizations. I don't want to provide that;
there is really no need.

Can you please manually bypass? I give you my approval via this email.

- M

**Comment by jouni** [comment]
Thanks, we’ll accept that as an agreement 👍

**Pull request merged**
