### PR TITLE
feat: explain the new `model` argument of `getFieldStrategy`

### LINKED ISSUE #1475: Update the custom strategy article to include the model argument in `getFieldStrategy`
The binder’s `getFieldStrategy` method now has the model argument added in https://github.com/vaadin/hilla/pull/421

Update the [custom strategy article](https://hilla.dev/docs/data-binding/web-component-field-strategy/#defining-a-field-strategy) to mention the new argument and that the model can affect the binding strategy.

### PR DESCRIPTION
**Pull request by cromoteca**
Closes #1475

### CODE REVIEW

**Review by Lodin — APPROVED** [review]

**Comment by cromoteca** [comment]
@russelljtdyer thank you for your review. We have this rule in our style guidelines: https://vaadin.com/docs/latest/contributing-docs/authoring/formatting/#source.one-line-per-sentence. Is that no longer relevant?

**Comment by cromoteca** [comment]
I understand, but this is a rule in our documentation. It's something you should discuss with the docs team, too decide if we keep this rule or not. It's not up to me to decide here.

**Comment by jouni** [comment]
> We have this rule in our style guidelines: https://vaadin.com/docs/latest/contributing-docs/authoring/formatting/#source.one-line-per-sentence. Is that no longer relevant? Also, Vale is now failing due to a long sentence.

Yeah, apologies for not updating the style guide to match. We discussed this with Russell a while ago, and I agreed that this rule is not worth enforcing. Personally, I don't have a strong preference either way. I have a work-in-progress branch for updating the docs contribution pages, but it gets pushed back in my todo. But I can at least make this quick adjustment right  away.

**Comment by cromoteca** [comment]
It was about the one line per sentence rule.

**Comment by jouni** [comment]
> It was about the one line per sentence rule.

Yes, I understood that (I see now that my comment was ambiguous). I removed the "one sentence per line" guideline now from the authoring guidelines.

**Pull request merged**
