### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by DaLLr0g**
Added hidden property to css.
Without this changes contact-form cannot be hidden.

### CODE REVIEW

**Comment by tarekoraby** [comment]
Thanks @DaLLr0g! But I'm failing to understand why it's necessary to `display:none`. Shouldn't the hidden attribute work regardless: https://thisthat.dev/display-none-vs-hidden-attribute/?

**Comment by tarekoraby** [comment]
It seems to be working for me when I run the [tutorial project](https://github.com/vaadin/flow-crm-tutorial) at least.

**Comment by DaLLr0g** [comment]
I was following by tutorial, and was surprised that my form didn't disappear.
Then I went to completed code in git and found that in tutorial was missed this code.

**Comment by DaLLr0g** [comment]
https://github.com/vaadin/hilla-crm-tutorial/blob/main/frontend/themes/hilla-crm/styles.css
You can find this here.

**Comment by tarekoraby** [comment]
Ah ok. Sorry, I didn't realize you were following the Hilla tutorial. I was talking about the Flow one. 

Yes, you are right. This extra styling is needed because the contact-form has the `flex` class, which takes priority over the `hidden` attribute (unless `important!` is used).

**Review by tarekoraby — APPROVED** [review]

**Comment by tarekoraby** [comment]
@DaLLr0g kindly sign the CLA to merge.

**Comment by DaLLr0g** [comment]
> @DaLLr0g kindly sign the CLA to merge.

done ✅

**Comment by tarekoraby** [comment]
Thanks for the contribution 🚀

**Pull request merged**
