### PR TITLE
[WIP] Update Notification event type and dialog event type in the Typescript examples for Vaadin 20

### PR DESCRIPTION
**Pull request by jcgueriaud1**
Update event types in the Typescript examples for Vaadin 20.
* Notification
* Dialog
* Accordion
* Confirm Dialog

[WIP] If I've got enough time I'll try to update the other examples.

### CODE REVIEW

**Comment by jouni** [comment]
Build errors:

```
6:36:31 PM: [ERROR] ERROR in /opt/build/repo/frontend/demo/component/accordion/accordion-summary.ts
6:36:31 PM: [ERROR] [tsl] ERROR in /opt/build/repo/frontend/demo/component/accordion/accordion-summary.ts(53,59)
6:36:31 PM: [ERROR]       TS2322: Type 'number | null' is not assignable to type 'number'.
6:36:31 PM: [ERROR]   Type 'null' is not assignable to type 'number'.
```

**Comment by jcgueriaud1** [comment]
I'll change the PR after this ticket: https://github.com/vaadin/web-components/issues/216

**Comment by jouni** [comment]
@jcgueriaud1, are you still working on this?

**Comment by jcgueriaud1** [comment]
No, I was waiting for this. https://github.com/vaadin/web-components/issues/216

This PR is probably useless since it's already outdated for v21.

**Pull request closed without merging**
