### PR TITLE
Restructure Flow documentation

### PR DESCRIPTION
**Pull request by jouni**
Depends on https://github.com/vaadin/docs-app/pull/319

Take advantage of the "section outline" feature in DSP: remove the explicit "Overview" pages (with the exception of the root-level ones), and move that content to the index/outline page of each section.

Simplify/cleanup top-level section titles (shorter, to the point).

Combine all component-related sections/articles under a joint "Components" section. Relocated the Flow Grid and Upload articles under their respective DS component docs pages ([Grid/Flow Usage](https://deploy-preview-984--vaadin-docs-preview.netlify.app/ds/components/grid/flow), [Upload/Flow Usage](https://deploy-preview-984--vaadin-docs-preview.netlify.app/ds/components/upload/flow)). Remove the Icon page, as those are already documented in two other places (Application Basics and DS/Foundation)

### CODE REVIEW

**Comment by jouni** [comment]
@tarekoraby, I’m about to merge the DSP "section outline" feature, and we can then go ahead with this PR, if we agree that the changes make sense.

**Review by tarekoraby — APPROVED** [review]

**Comment by tarekoraby** [comment]
Approved. For future PR(s), we should work on improving the overview pages of the sections.

**Comment by jouni** [comment]
I’ll need to prepare some redirects related to this, before merging.

**Comment by jouni** [comment]
I managed to create a bit of a mess with the rebase (after #950). Closing in favor of #1008

**Pull request closed without merging**
