### PR TITLE
Replace old hilla.dev links from v23

### PR DESCRIPTION
**Pull request by veerapaananen**
Old hilla.dev links redirect to vaadin.com now. This fix replaces those links in the docs for version 23 with the final addresses they currently redirect to, removing the old links pointing to hilla.dev and removing redirections.

Example:

Old link: https://hilla.dev/
New link: https://vaadin.com/hilla

### CODE REVIEW

**Comment by peholmst** [comment]
V23 Hilla links should not point to the latest version of Hilla, but the to the version that works with Vaadin 23. Unfortunately that documentation is currently not available anywhere.

**Comment by veerapaananen** [comment]
Those links redirect now to the latest documentation anyway. Should the links be removed instead? @peholmst

**Comment by peholmst** [comment]
Given the situation right now, they should be removed. But if we end up publishing the documentation for the old Hilla versions somewhere, they would have to be added back.

**Comment by veerapaananen** [comment]
I'll do some changes and update this PR. Let's add the links back if/when the old Hilla docs are published.

**Review by peholmst — APPROVED** [review]

**Pull request merged**
