### PR TITLE
chore: Upgrade Spring to 2.6.1

### PR DESCRIPTION
**Pull request by tarekoraby**

### CODE REVIEW

**Comment by jouni** [comment]
I assume you tested this locally? The Netlify preview build doesn't run the Java server, so that needs to be verified locally.

**Comment by tarekoraby** [comment]
`mvn clean install` runs fine locally.

**Comment by tomivirkki** [comment]
> `mvn clean install` runs fine locally.

What should be tested is actually starting up the docs project locally (`mvn`) and then testing (with the docs viewer app) that the embedded Java examples etc work.

**Comment by tarekoraby** [comment]
The project actually doesn't start with Spring Boot `2.6.1`. I believe there is a fix for that coming soon with Vaadin `22.0.2`. Let's wait for that.

**Comment by tarekoraby** [comment]
Tested locally with Vaadin 22.0.2 + Spring 2.6.1, and everything seems to be running fine.

**Review by tomivirkki — APPROVED** [review]
Confirmed this works now and actually fixes the issue with the server currently not starting at all

**Pull request merged**
