### PR TITLE
chore: fix dspublisher-scripts after flow adding type:module

### PR DESCRIPTION
**Pull request by manolo**
It should fix https://github.com/vaadin/docs/issues/3328 but not sure there could be more scripts failing.

### CODE REVIEW

**Comment by ZheSun88** [comment]
@tomivirkki  there are probably more of this kind files. 
for example, you have mentioned 
```
https://github.com/vaadin/docs/blob/next/dspublisher/dspublisher-scripts.js
https://github.com/vaadin/docs/blob/next/webpack.dspublisher.js
https://github.com/vaadin/docs/blob/next/dspublisher/theme/init.js
```

anything more?

**Comment by ZheSun88** [comment]
i need this change to make the code work on Windows. 
image

**Comment by tomivirkki** [comment]
> how should i find them?

You can search for `require(` in the project to discover some cjs files

**Comment by ZheSun88** [comment]
after fixing the `init.js`, error is now coming from dsp, will check after dsp got updated.

```
require() of ES Module *\docs\dspublisher\theme\init.js from
*\AppData\Local\npm-cache\_npx\d94b02936b9f011a\node_modules\@vaadin\
dspublisher\gatsby-node.js not supported.
Instead change the require of init.js in *\AppData\Local\npm-cache\_n
px\d94b02936b9f011a\node_modules\@vaadin\dspublisher\gatsby-node.js to a dynamic
 import() which is available in all CommonJS modules.

  44 |   const docsThemeInit = path.resolve(contentRoot, themePath, 'init.js');
  45 |   if (fs.existsSync(docsThemeInit)) {
> 46 |     const docsThemeInitExport = require(docsThemeInit);
     |                                 ^
  47 |     if (typeof docsThemeInitExport === 'function') {
  48 |       await docsThemeInitExport();
  49 |     }

```

**Review by tomivirkki — APPROVED** [review]

**Review by ZheSun88 — APPROVED** [review]

**Pull request merged**
