### PR TITLE
docs: ported and reworked Customizing System Messages documentation

### LINKED ISSUE #1699: V23 docs missing CustomizedSystemMessages
The possibility of customizing system messages is not available in the V14 or V23 documentation. For V8, the instructions are found here: https://vaadin.com/docs/v8/framework/application/application-errors/#application.errors.systemmessages ; the functionality hasn't changed to my knowledge.

### PR DESCRIPTION
**Pull request by mcollovati**
Documentation for Customizing System Messages was present in Vaadin 8 but not ported to Flow.

Fixes #1699

### CODE REVIEW

**Review by caalador — COMMENTED** [review]
Only thing that I would perhaps like to know that is not specifically mentioned is the default status for the different messages.
`sessionExpired` is disabled by default, where as `internalError` and `cookiesDisabled` are enabled.
`CustomizedSystemMessages` doesn't say the default state in the Javadoc either

**Comment by mcollovati** [comment]
> `CustomizedSystemMessages` doesn't say the default state in the Javadoc either

Defaults are documented int `SystemMessages` Javadoc.
But it absolutely makes sense to list them also on documentation

**Comment by caalador** [comment]
I did note that statement, but it doesn't directly connect to `sessionExpiredNotificationEnabled` so it would be good to have the different enabled defaults written out in the document.
Also on the `SystemMessages` I only looked at the getter and setter javadoc and those do not say the default.

**Comment by mcollovati** [comment]
> Also on the `SystemMessages` I only looked at the getter and setter javadoc and those do not say the default.

Good point.
Getter/Setter Javadocs are the first ones that a developer will look at. It would be good to update them

**Review by caalador — APPROVED** [review]

**Pull request merged**
