### PR TITLE
feat: add articles for React interaction components

### LINKED ISSUE #1843: Interaction components article
Describe React component wrappers for the following Vaadin components with at least one code example per component, in priority order:

```
vaadin-button
vaadin-grid
vaadin-virtual-list
vaadin-dialog / confirm-dialog
vaadin-tabs / tab
vaadin-details
vaadin-scroller
```

### PR DESCRIPTION
**Pull request by cromoteca**
Closes #1843

### CODE REVIEW

**Comment by jouni** [comment]
Note, that I changed the HeadingCase Vale check for Hilla docs to use "Sentence case", instead of "Title Case". So please update the new headings to use that instead. I’m updating those gradually for the rest of the documentation while I’m refactoring it.

**Comment by cromoteca** [comment]
> Note, that I changed the HeadingCase Vale check for Hilla docs to use "Sentence case", instead of "Title Case". 

What about component names? Isn't "Confirm Dialog" supposed to be title case?

**Comment by jouni** [comment]
Yes, component names should be in title case still.

**Comment by cromoteca** [comment]
Merged into #1855

**Pull request closed without merging**
