### PR TITLE
docs: Copilot 24.5 docs update

### PR DESCRIPTION
**Pull request by MarcinVaadin**
Documentation update after 24.5 release.

Fixes: https://github.com/vaadin/copilot-internal/issues/2969
Fixes: https://github.com/vaadin/copilot-internal/issues/2296
Fixes: https://github.com/vaadin/copilot-internal/issues/2624
Fixes: https://github.com/vaadin/copilot-internal/issues/3716

### CODE REVIEW

**Review by emarc — APPROVED** [review]
👍

**Review by emarc — APPROVED** [review]
LGTM

**Comment by MarcinVaadin** [comment]
@jouni can that PR be merged?

**Comment by jouni** [comment]
@MarcinVaadin, yeah, sure. I’ll pull the trigger personally. I assume it’s the failing preview build that’s preventing the auto-merge. I think we’re working on fixing the preview build.

**Pull request merged**
