### PR TITLE
Described how to use new `VaadinSpringSecurity` helper

### PR DESCRIPTION
**Pull request by joheriks**
Part of vaadin/spring#678.

### CODE REVIEW

**Review by haijian-vaadin — CHANGES_REQUESTED** [review]
Should we also show how to use the other 2 helper methods? `getDefaultHttpSecurityPermitMatcher` and `getDefaultWebSecurityIgnoreMatcher`. For example, a user might want to set up a custom matcher based on the default one?

**Comment by joheriks** [comment]
> Should we also show how to use the other 2 helper methods? `getDefaultHttpSecurityPermitMatcher` and `getDefaultWebSecurityIgnoreMatcher`. For example, a user might want to set up a custom matcher based on the default one?

Can do. Just wondering where would be the best place to add it, `spring-login.asciidoc`?

**Comment by haijian-vaadin** [comment]
> > Should we also show how to use the other 2 helper methods? `getDefaultHttpSecurityPermitMatcher` and `getDefaultWebSecurityIgnoreMatcher`. For example, a user might want to set up a custom matcher based on the default one?
> 
> Can do. Just wondering where would be the best place to add it, `spring-login.asciidoc`?

`spring-login.asciidoc` sounds a good place.

**Comment by joheriks** [comment]
> > > Should we also show how to use the other 2 helper methods? `getDefaultHttpSecurityPermitMatcher` and `getDefaultWebSecurityIgnoreMatcher`. For example, a user might want to set up a custom matcher based on the default one?
> > 
> > 
> > Can do. Just wondering where would be the best place to add it, `spring-login.asciidoc`?
> 
> `spring-login.asciidoc` sounds a good place.

Done.

**Review by haijian-vaadin — APPROVED** [review]

**Pull request merged**
