### PR TITLE
chore: restore and extend OSGi docs

### PR DESCRIPTION
**Pull request by denis-anisimov**

### CODE REVIEW

**Comment by jouni** [comment]
@denis-anisimov, could you fix as many of the [writing style guide errors and warnings](https://github.com/vaadin/docs/pull/40/files) as possible?

**Comment by jouni** [comment]
Also, if you are not sure how to correct some of the errors or warnings, just leave them. We will fix those before merging. But all the fixes you can make will get this merged faster.

**Comment by jouni** [comment]
Actually, I think I can handle this PR, as this ended up being a nice test case for the Vale linting process. @denis-anisimov, apologies for any extra annoyance this might’ve caused 🤗

**Comment by denis-anisimov** [comment]
> Actually, I think I can handle this PR, as this ended up being a nice test case for the Vale linting process. @denis-anisimov, apologies for any extra annoyance this might’ve caused 🤗

Oh, I'm sorry @jouni , I haven't checked your comments here because I have a filter for the notifications from this repo :(

**Comment by denis-anisimov** [comment]
But I hope things are already fixed.

Sorry one more time.

**Comment by jouni** [comment]
😄 No worries! This was a good test case for the review process for myself.

**Comment by denis-anisimov** [comment]
Alright, good that it even served for a good purpose.

**Pull request merged**
