### PR TITLE
Show React docs cards at root

### PR DESCRIPTION
**Pull request by tarekoraby**
Disclaimer: I didn't test this change as I cannot run the docs locally.

### CODE REVIEW

**Comment by jouni** [comment]
The React index page was missing the tagged region. I added that. Here’s how it looks like, with the top level sections explicitly expanded in the side nav:
Screenshot 2023-09-21 at 16 13 01

**Comment by jouni** [comment]
Need to restore `root: true` at least.

**Comment by jouni** [comment]
After fixes:
Screenshot 2023-09-21 at 16 22 57

**Comment by tarekoraby** [comment]
I think that serves as a good band-aid for now. We can revisit the topic and think of other ideas later. Feel free to merge at any time.

**Pull request merged**
