### PR TITLE
Use Frontend root path alias in TypeScript

### PR DESCRIPTION
**Pull request by platosha**
Connected to vaadin/flow#9544

### CODE REVIEW

**Review by haijian-vaadin — APPROVED** [review]

**Comment by jouni** [comment]
FYI, I just merged App Layout examples, and I believe they also need this update.

**Comment by haijian-vaadin** [comment]
since v19 is released, we can mark the PR as ready and merge it?

**Comment by haijian-vaadin** [comment]
Got same errors as in https://github.com/vaadin/docs/pull/169#issuecomment-799490291

**Review by haijian-vaadin — APPROVED** [review]

**Comment by haijian-vaadin** [comment]
Looks good to me, could you @jouni help to merge it?

**Pull request merged**
