### PR TITLE
Use endpoint wrapper exports

### PR DESCRIPTION
**Pull request by platosha**
Connected to vaadin/flow#7176
Depends on vaadin/flow#9972
Depends on #152

### CODE REVIEW

**Comment by jouni** [comment]
Build error:

```

8:19:43 PM: ERROR in [at-loader] ./frontend/demo/fusion/forms/contact-form.ts:8:10
8:19:43 PM:     TS2305: Module '"../../../generated/ContactEndpoint"' has no exported member 'ContactEndpoint'.
8:19:43 PM: ERROR in [at-loader] ./frontend/demo/pwa/offline/ts-view-with-endpoint.ts:4:10
8:19:43 PM:     TS2305: Module '"../../../generated/DataEndpoint"' has no exported member 'DataEndpoint'.
```

**Comment by platosha** [comment]
@jouni thanks for noting. As described, this depends on the future feature in https://github.com/vaadin/flow/pull/9972, which is not yet merged. This PR is marked as a WIP draft for now because of this.

Sorry for the noise.

**Comment by haijian-vaadin** [comment]
We can now mark it as ready and merge it?

**Review by haijian-vaadin — CHANGES_REQUESTED** [review]
See some build errors
```
3:18:10 PM: ERROR in /opt/build/repo/frontend/demo/component/login/login-modal-overlay.ts
3:18:10 PM: [tsl] ERROR in /opt/build/repo/frontend/demo/component/login/login-modal-overlay.ts(16,4)
3:18:10 PM:       TS2304: Cannot find name 'internalProperty'.
3:18:10 PM: ERROR in /opt/build/repo/frontend/demo/fusion/forms/contact-form.ts
3:18:10 PM: [tsl] ERROR in /opt/build/repo/frontend/demo/fusion/forms/contact-form.ts(8,10)
3:18:10 PM:       TS2305: Module '"../../../generated/ContactEndpoint"' has no exported member 'ContactEndpoint'.
3:18:10 PM: ERROR in /opt/build/repo/frontend/demo/pwa/offline/ts-view-with-endpoint.ts
3:18:10 PM: [tsl] ERROR in /opt/build/repo/frontend/demo/pwa/offline/ts-view-with-endpoint.ts(4,10)
3:18:10 PM:       TS2305: Module '"../../../generated/DataEndpoint"' has no exported member 'DataEndpoint'.
```

**Comment by platosha** [comment]
@haijian-vaadin should be fixed now. Fixing required bumping platform version to `20.0.0.alpha3`

**Comment by haijian-vaadin** [comment]
> @haijian-vaadin should be fixed now. Fixing required bumping platform version to `20.0.0.alpha3`

The deoploy/nelitfy link gives page not found error. I tried to deploy it locally, found that there are some build errors remaining.
```
SyntaxError: /Users/haijian/Documents/workspace/docs/frontend/demo/component/dialog/dialog-basic.ts: Unexpected token (9:0)

   7 | import '@vaadin/vaadin-dialog/vaadin-dialog';
   8 | import '@vaadin/vaadin-button/vaadin-button';
>  9 | <<<<<<< HEAD
     | ^
  10 | =======
  11 | import '@vaadin/vaadin-text-field/vaadin-text-field';
  12 | import '@vaadin/vaadin-ordered-layout/vaadin-horizontal-layout';
    at Object._raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Object.raiseWithData (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Object.raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:41:17)
    at Object.unexpected (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/util.js:161:16)
    at Object.parseExprAtom (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:1205:20)
    at Object.parseExprSubscripts (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:608:23)
    at Object.parseUpdate (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:588:21)
    at Object.parseMaybeUnary (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:555:23)
    at Object.parseMaybeUnary
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2629:22)
    at Object.parseExprOps (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:363:23)
    at Object.parseMaybeConditional (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:328:23)
    at Object.parseMaybeAssign (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:283:21)
    at Object.parseMaybeAssign
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2556:22)
    at Object.parseExpressionBase (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:203:23)
    at callback (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:196:39)
    at Object.allowInAnd (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:2598:16)
warn Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
SyntaxError: /Users/haijian/Documents/workspace/docs/frontend/demo/component/login/login-modal-overlay.ts: Unexpected token (3:0)

  1 | import 'Frontend/demo/init'; // hidden-full-source-line
  2 |
> 3 | <<<<<<< HEAD
    | ^
  4 | import { html, LitElement, customElement } from 'lit-element';
  5 | =======
  6 | import { html, LitElement, customElement, internalProperty } from 'lit-element';
    at Object._raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Object.raiseWithData (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Object.raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:41:17)
    at Object.unexpected (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/util.js:161:16)
    at Object.parseExprAtom (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:1205:20)
    at Object.parseExprSubscripts (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:608:23)
    at Object.parseUpdate (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:588:21)
    at Object.parseMaybeUnary (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:555:23)
    at Object.parseMaybeUnary
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2629:22)
    at Object.parseExprOps (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:363:23)
    at Object.parseMaybeConditional (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:328:23)
    at Object.parseMaybeAssign (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:283:21)
    at Object.parseMaybeAssign
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2556:22)
    at Object.parseExpressionBase (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:203:23)
    at callback (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:196:39)
    at Object.allowInAnd (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:2598:16)

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'Frontend/init' in '/Users/haijian/Documents/workspace/docs/frontend/demo/component/combobox'

If you're trying to use a package make sure that 'Frontend/init' is installed. If you're trying to use a local file make sure that the path
is correct.

File: ../docs/frontend/demo/component/combobox/combo-box-filtering-2.ts

failed Building development bundle - 40.905s
success onPreExtractQueries - 0.043s
success extract queries from components - 0.099s
success write out requires - 0.005s
warn "export 'ContactEndpoint' was not found in 'Frontend/generated/ContactEndpoint'
warn "export 'DataEndpoint' was not found in 'Frontend/generated/DataEndpoint'
warn Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
SyntaxError: /Users/haijian/Documents/workspace/docs/frontend/demo/component/dialog/dialog-basic.ts: Unexpected token (9:0)

   7 | import '@vaadin/vaadin-dialog/vaadin-dialog';
   8 | import '@vaadin/vaadin-button/vaadin-button';
>  9 | <<<<<<< HEAD
     | ^
  10 | =======
  11 | import '@vaadin/vaadin-text-field/vaadin-text-field';
  12 | import '@vaadin/vaadin-ordered-layout/vaadin-horizontal-layout';
    at Object._raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Object.raiseWithData (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Object.raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:41:17)
    at Object.unexpected (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/util.js:161:16)
    at Object.parseExprAtom (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:1205:20)
    at Object.parseExprSubscripts (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:608:23)
    at Object.parseUpdate (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:588:21)
    at Object.parseMaybeUnary (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:555:23)
    at Object.parseMaybeUnary
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2629:22)
    at Object.parseExprOps (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:363:23)
    at Object.parseMaybeConditional (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:328:23)
    at Object.parseMaybeAssign (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:283:21)
    at Object.parseMaybeAssign
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2556:22)
    at Object.parseExpressionBase (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:203:23)
    at callback (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:196:39)
    at Object.allowInAnd (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:2598:16)
warn Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
SyntaxError: /Users/haijian/Documents/workspace/docs/frontend/demo/component/login/login-modal-overlay.ts: Unexpected token (3:0)

  1 | import 'Frontend/demo/init'; // hidden-full-source-line
  2 |
> 3 | <<<<<<< HEAD
    | ^
  4 | import { html, LitElement, customElement } from 'lit-element';
  5 | =======
  6 | import { html, LitElement, customElement, internalProperty } from 'lit-element';
    at Object._raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Object.raiseWithData (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Object.raise (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/error.js:41:17)
    at Object.unexpected (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/util.js:161:16)
    at Object.parseExprAtom (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:1205:20)
    at Object.parseExprSubscripts (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:608:23)
    at Object.parseUpdate (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:588:21)
    at Object.parseMaybeUnary (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:555:23)
    at Object.parseMaybeUnary
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2629:22)
    at Object.parseExprOps (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:363:23)
    at Object.parseMaybeConditional (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:328:23)
    at Object.parseMaybeAssign (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:283:21)
    at Object.parseMaybeAssign
(/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/plugins/typescript/index.js:2556:22)
    at Object.parseExpressionBase (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:203:23)
    at callback (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:196:39)
    at Object.allowInAnd (/Users/haijian/Documents/workspace/docs-app/node_modules/@babel/parser/src/parser/expression.js:2598:16)

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'Frontend/init' in '/Users/haijian/Documents/workspace/docs/frontend/demo/component/combobox'

If you're trying to use a package make sure that 'Frontend/init' is installed. If you're trying to use a local file make sure that the path
is correct.
```

**Comment by platosha** [comment]
@haijian-vaadin 
> `Can't resolve 'Frontend/init' in '/Users/haijian/Documents/workspace/docs/frontend/demo/component/combobox'`

Fixed this one.

The reset seems to be some sort of merge conflict in the working copy. I cannot find any fragments like this in the commited files:
```
> 3 | <<<<<<< HEAD
    | ^
  4 | import { html, LitElement, customElement } from 'lit-element';
  5 | =======
  6 | import { html, LitElement, customElement, internalProperty } from 'lit-element';
```

**Comment by platosha** [comment]
The deploy/nelitfy is also working now.

**Review by haijian-vaadin — APPROVED** [review]

**Comment by haijian-vaadin** [comment]
Looks good to me, could @jouni help to merge it?

**Comment by jouni** [comment]
Apparently another merge introduced conflicts.

**Comment by platosha** [comment]
Rebased on `latest` and added missing endpoint wrappers for new code examples.

**Pull request merged**
