### PR TITLE
feat: setup for docbuilder

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes https://github.com/vaadin/docs-app/issues/106
Fixes https://github.com/vaadin/docs-app/issues/200

This PR adds commands for developing and building the project using the [Docbuilder image](https://github.com/vaadin/docs-app/pull/211).

Prerequisites:
- Docker installed https://docs.docker.com/get-docker/
- Java, Maven, and NodeJS installed (for license checking purposes)
- Docbuilder image [installed locally](https://github.com/vaadin/docs-app/pull/211) (not yet published to Docker Hub)

Testing the PR:
1. Make sure your environment is clean `npm run docbuilder:clean`
2. Start-up the app in development mode: `npm run docbuilder:start`
   - Note that the first run will take a lot of time. Subsequent runs will be faster
   - Once the server is up and running, the app is available at [`localhost:8000`](http://localhost:8000)
3. Build the app: `npm run docbuilder:build`
   - Note that the first run will take a lot of time. Subsequent runs will be faster
   - Once the build is complete, you can find the following build artifacts
     - `/docbuilder/build/out/[docs].jar` (the docs Vaadin project production build jar)
     - `/docbuilder/build/out/public` (the static pages build by docs-app)
   - You can configure the build with environment variables listed [here](https://github.com/vaadin/docs-app#list-of-environment-variables)
     - example: `DOCS_PATH_PREFIX=/docs/latest npm run docbuilder:build`
     - alternatively, you can create an `.env` file with the `key="value"` pairs under `docbuilder/develop` and `docbuilder/build` and start with `npm run docbuilder:build`
4. The build artifacts from the previous steps can be deployed in various different ways. This PR adds one deployment example (using Docker compose)
  4.1. `cd docbuilder/build/deployment-example-docker`
  4.2. `docker-compose up`
     - Once the server is up and running, the app is available at [`localhost:80`](http://localhost:80)

### CODE REVIEW

**Comment by jouni** [comment]
I don’t know what I’m doing wrong, but I can’t get any asciidoc changes to come visible when running in dev mode.

**Comment by jouni** [comment]
Ah, it might be because I missed the instructions how to clean the environment. I’ll see if that helps.

**Comment by jouni** [comment]
Now it’s been hanging on the following for a while. I’m unsure if it’s still doing something, but judging from the spinning fans on my laptop, something is still happening 😄 

```
...
docs_1      | npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
docs_1      | npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
docs_1      | npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
docs_1      | npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
docs_1      | npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
docs_1      | npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

**Comment by tomivirkki** [comment]
It's running `npm install` in the `docs` project. Please wait :)

**Comment by jouni** [comment]
Alright, up and running again, after running `npm run docbuilder:clean`. Still not getting asciidoc updates visible in the browser. I get this in the terminal:

```
docs-app_1  | info changed file at /docs/articles/ds/foundation/typography/index.asciidoc
docs-app_1  | success building schema - 4.596s
docs-app_1  | info Total nodes: 1708, SitePage nodes: 413 (use --verbose for breakdown)
docs-app_1  | success createPages - 17.447s
docs-app_1  | success Checking for changed pages - 0.019s
docs-app_1  | success update schema - 3.115s
docs-app_1  | success onPreExtractQueries - 0.002s
docs-app_1  | success extract queries from components - 0.117s
docs-app_1  | success write out requires - 0.006s
docs-app_1  | success run page queries - 0.016s - 1/1 61.04/s
```

But the page stays the same even after reload.

**Comment by tomivirkki** [comment]
Kapture 2021-02-03 at 11 39 05

**Comment by jouni** [comment]
Right, now I got the update visible. It was a user error – I was trying to update the main page heading ("Typography"), but since it’s tabbed-page, that text comes from the frontmatter and not from the h1 🤦 

But the time it took to see the update is over 40 seconds 🕐 
What do I need to do to make it faster?

https://user-images.githubusercontent.com/66382/106768465-9cd5d200-6644-11eb-9faf-3666f157611f.mov

**Review by jouni — APPROVED** [review]
Very slow for me, but works. Only tested running the development server and updating asciidoc content.

**Pull request merged**
