### PR TITLE
refactor: use theme variant constants in Flow examples

### PR DESCRIPTION
**Pull request by sissbruecker**
## Description

Updates existing Flow examples to use theme variant constants where possible.

### CODE REVIEW

**Comment by vursen** [comment]
I would also suggest simplifying another example within the PR. 

Instead of:
https://github.com/vaadin/docs/blob/e8842ebf3c17e33636c92b05623fc3d9a3298188/src/main/java/com/vaadin/demo/component/inputfields/InputFieldHelperPosition.java#L17

Do this:
```java
textField.addThemeVariants(TextFieldVariant.LUMO_HELPER_ABOVE_FIELD);
```

**Comment by vursen** [comment]
Would it make sense to use a Lumo theme variant for `MoneyField`?

https://github.com/vaadin/docs/blob/7f3fb14b0d3923031eb2172e22e46e8c4070159d/src/main/java/com/vaadin/demo/component/customfield/CustomFieldSizeVariants.java#L13

**Comment by sissbruecker** [comment]
> Would it make sense to use a Lumo theme variant for `MoneyField`?
> 
> https://github.com/vaadin/docs/blob/7f3fb14b0d3923031eb2172e22e46e8c4070159d/src/main/java/com/vaadin/demo/component/customfield/CustomFieldSizeVariants.java#L13

MoneyField is a custom component built for the examples, it doesn't have to have the same API as the official components.

**Comment by vursen** [comment]
I noticed that some of the Button examples import variants in the following manner:

```java
import static com.vaadin.flow.component.button.ButtonVariant.*;

...

button.addThemeVariants(LUMO_PRIMARY);
```

Would it be reasonable to align these with other examples within the current PR? So that, instead, it would do:

```java
import static com.vaadin.flow.component.button.ButtonVariant;

...

button.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
```

**Review by vursen — APPROVED** [review]

**Pull request merged**
