### PR TITLE
feat: Add documentation about custom theme

### PR DESCRIPTION
**Pull request by caalador**
Add the custom theme feature documentation
to v14 branch.

Part of vaadin/flow#9983

### CODE REVIEW

**Comment by jouni** [comment]
I think this is outdated already, as the article titles are different than in latest.

**Comment by caalador** [comment]
So there has been changes to 14? master? after yesterday around 15?

**Comment by jouni** [comment]
Please check the cross references. At least the following is broken:

```
error Broken cross reference ../../flow/integrations/embedding/overview in flow/styling/custom-theme.asciidoc
```

**Comment by jouni** [comment]
One more thing: please delete the old `creating-a-custom-theme.asciidoc` article.

**Comment by caalador** [comment]
Well it's sort of valid for 14 and in 14.6 you can have your own `Theme extends Lumo` in combination with the new custom theme feature.
@pleku what do you think about the `extends AbstractTheme` documentation.

**Comment by jouni** [comment]
Ah, right, sorry about. I got confused about this, that it was the previous new V19 article. 

But at least the article title (and file name) should be updated. We shouldn’t have two “Creating a Custom Theme” articles.

**Comment by pleku** [comment]
I think there needs to be note in the old article that "it doesn't apply after 14.6 since, while it still works, the new custom theme feature that should be used"

**Review by jouni — APPROVED** [review]

**Pull request merged**
