### PR TITLE
It points to the v14 directory.

### PR DESCRIPTION
**Pull request by KouichiNoro**
This is v20 documents but link is v14 documents.

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by jouni — APPROVED** [review]

**Comment by jouni** [comment]
Thanks for noticing and providing the fix!

**Comment by jouni** [comment]
Oh, actually, the v20 branch doesn’t contain Flow In-Depth Course, so the links have to point to the other branch. We do have the tutorial in the latest docs branch, though, so we should fix it there.

**Comment by jouni** [comment]
I’m not sure we are going to backport the tutorials to the v20 branch (it only has about a month until it will be removed), so I’m closing this for now.

**Comment by jouni** [comment]
Fix for latest in https://github.com/vaadin/docs/commit/dbf33e62346f6722c792d62bb776dcfd615db63d

**Comment by jouni** [comment]
Fix for v21 branch in https://github.com/vaadin/docs/commit/cfa5b18a40f82c30783adc34536ed7b106c913e5

**Comment by KouichiNoro** [comment]
Thank you for the article, I see you don't make v20 documents. I understand. I'm sorry I'm being so rude.

**Comment by jouni** [comment]
No need to apologies 🤗 Again, thank you for pointing out this issue, so that we got to fix it 👍

**Pull request closed without merging**
